### ISSUE TITLE
volume display incorrect

### ISSUE THREAD

**Issue by a16547** [System64fumo/syshud#10]
The volume should be 15% instead of 14%
It appears as 15% in the waybar

![2024-09-08 00-21-54](https://github.com/user-attachments/assets/932d38b7-d7c2-4518-b44d-4e33a02af739)

**Comment by kRHYME7** [comment]
@a16547  

Hi this is unrelated but I needed some help. I saw on your screenshot that this project works on volume change.

`monitors=audio_in,audio_out,brightness ` 
Should this config work for volume, I can't seem to display the volume. Only the brightness works on my end.

If yes, I should open a separate issue.

**Comment by System64fumo** [comment]
@a16547 

Volume calculations differ from device to device, There is some rounding that happens since volume levels are.. Quite funky to say the least, Either way i can't really debug this besides making a wild guess on how much i should round things up which could fix your issue and break it for someone else.

I will see what i can do tomorrow, No guarantees though.
![screenshot](https://github.com/user-attachments/assets/aec9f8ee-4658-47a2-a357-e20df0d61d1c)

**Comment by System64fumo** [comment]
@kRHYME7 Yeah open another issue, This is unrelated to this.

**Comment by a16547** [comment]
With reference to the implementation of [waybar](https://github.com/Alexays/Waybar/blob/master/src/modules/wireplumber.cpp#L318), the following patches work for me

```diff
diff --git a/src/wireplumber.cpp b/src/wireplumber.cpp
index 4a0e770..5b20bef 100644
--- a/src/wireplumber.cpp
+++ b/src/wireplumber.cpp
@@ -1,4 +1,5 @@
 #include "wireplumber.hpp"
+#include <cmath>
 
 bool syshud_wireplumber::isValidNodeId(uint32_t id) {
        return id > 0 && id < G_MAXUINT32;
@@ -29,7 +30,7 @@ void syshud_wireplumber::onMixerChanged(syshud_wireplumber* self, uint32_t id) {
                                                        WP_PIPEWIRE_OBJECT(node), "media.class"));
 
        // Set values and trigger a callback
-       self->volume = (temp_volume + 0.000001) * 100.0;
+       self->volume = std::round(temp_volume * 100.0);
        if (media_class == "Audio/Source") {
                if (self->input_callback != nullptr)
                        self->input_callback->emit();
```

**Comment by System64fumo** [comment]
Funnily enough this is how i did my rounding too since i originally based my code on waybar's wireplumber module, However i've gotten rid of that implementation in favor of simpler rounding since i would rather reduce unnecessary external includes/libraries.

I would suggest you remove a few zeros from the line mentioned and see how it goes, Otherwise i will revert back go the previous working method.

**Comment by a16547** [comment]
```diff
diff --git a/src/wireplumber.cpp b/src/wireplumber.cpp
index 4a0e770..bf68c0b 100644
--- a/src/wireplumber.cpp
+++ b/src/wireplumber.cpp
@@ -29,7 +29,7 @@ void syshud_wireplumber::onMixerChanged(syshud_wireplumber* self, uint32_t id) {
                                                        WP_PIPEWIRE_OBJECT(node), "media.class"));
 
        // Set values and trigger a callback
-       self->volume = (temp_volume + 0.000001) * 100.0;
+       self->volume = (temp_volume + 0.0001) * 100.0;
        if (media_class == "Audio/Source") {
                if (self->input_callback != nullptr)
                        self->input_callback->emit();
```
it work
