### ISSUE TITLE
support for stuff like num lock and caps lock?

### ISSUE THREAD

**Issue by littleblack111** [System64fumo/syshud#9]

**Comment by System64fumo** [comment]
Sure why not.
I'll take a look tomorrow when i get time, Great suggestion!

**Comment by littleblack111** [comment]
ty!

**Comment by System64fumo** [comment]
@littleblack111 I'm done cooking, Let me know if this is what you were looking for.

Things to note:
It's disabled by default so you will need to add "keyboard" to your monitors in your config
You will also need to add the keyboard=/dev/input/by-id/path-to-kbd config too
You're likely gonna want to wait if you want to enable this on portable devices since the current implementation is quite yucky (Check the keyboard state every 100ms)

My keyboard doesn't have scroll lock so i can't really test that, Should work just fine though :|

**Comment by littleblack111** [comment]
sry, just seen it. nice!
